### ISSUE TITLE
incorrect key generation for properties

### ISSUE THREAD

**Issue by kennethrapp** [sonoro1234/LuaJIT-SDL3#1]
The keys for SDL3's properties API are char* but the FFI generates them as const int. 

![Clipboard01](https://github.com/user-attachments/assets/58b3cb4d-241b-4041-9dd3-326b97121936)

**Comment by sonoro1234** [comment]
LuaJIT does not allow `static const char*` so that now this string defines are located in table `sdl3.strdef`

**Comment by sonoro1234** [comment]
Also gettable from sld3: `sdl.SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN` or `sdl.strdef.SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN`

**Comment by kennethrapp** [comment]
OK thanks.
